# -*- coding: utf-8 -*-
"""CV_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwb5xxvUO5RW4jACLRTL9zRWHtcgMVUi
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load YOLO model
net = cv2.dnn.readNet("yolov4.weights", "yolov4.cfg")
layer_names = net.getLayerNames()
output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]
classes = open("coco.names").read().strip().split("\n")

# Load the video
video_path = "/content/Video.mp4"  # Change to your video file
cap = cv2.VideoCapture(video_path)

# Get original video properties
frame_width = int(cap.get(3))   # Original width
frame_height = int(cap.get(4))  # Original height
fps = int(cap.get(5))           # Original frame rate

# Video writer (same resolution & FPS as input)
out = cv2.VideoWriter("output.avi", cv2.VideoWriter_fourcc(*'XVID'), fps, (frame_width, frame_height))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break  # Stop if video ends

    height, width, _ = frame.shape  # Keep original dimensions

    # Convert frame to blob (without rescaling)
    blob = cv2.dnn.blobFromImage(frame, 1/255.0, (416, 416), swapRB=True, crop=False)
    net.setInput(blob)
    detections = net.forward(output_layers)

    boxes, confidences, class_ids = [], [], []

    # Process detections
    for output in detections:
        for detection in output:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]

            if confidence > 0.5:
                center_x, center_y, w, h = map(int, detection[:4] * [width, height, width, height])
                x, y = int(center_x - w / 2), int(center_y - h / 2)
                boxes.append([x, y, w, h])
                confidences.append(float(confidence))
                class_ids.append(class_id)

    # Apply Non-Maximum Suppression (NMS)
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)

    # Draw bounding boxes (keeping original frame size)
    for i in indexes.flatten():
        x, y, w, h = boxes[i]
        label = f"{classes[class_ids[i]]}: {confidences[i]:.2f}"
        color = (0, 255, 0)
        cv2.rectangle(frame, (x, y), (x + w, y + h), color, 2)
        cv2.putText(frame, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    # Save and display the frame without resizing
    out.write(frame)
    cv2_imshow(frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break  # Press 'q' to stop

# Release resources
cap.release()
out.release()
cv2.destroyAllWindows()